### PR TITLE
Prevent SQL Injection

### LINKED ISSUE #56: [BUG] Hana user parse privilege issue
**Describe the bug**
Creating HANA users with the following privilege: `REFERENCES ON PSE _SAP_DB_ACCESS_PSE_CLIENT_IDENTITY` fails with the following error:

```
cannot convert privileges: failed to parse privilege REFERENCES ON PSE _SAP_DB_ACCESS_PSE_CLIENT_IDENTITY: unknown type of privilege: REFERENCES ON PSE _SAP_DB_ACCESS_PSE_CLIENT_IDENTITY
```

**Tested with Provider Version**
v0.2.0

**To Reproduce**

Create User with the following privilege:

```yaml
spec:
  forProvider:
    privileges:
    - REFERENCES ON PSE _SAP_DB_ACCESS_PSE_CLIENT_IDENTITY
```

### PR DESCRIPTION
**Pull request by yamaceay**
Fixes #56

### CODE REVIEW

File: internal/clients/hana/auditpolicy/auditpolicy_client.go [hunk 1]
```diff
@@ -151,32 +155,249 @@ func (c Client) Delete(ctx context.Context, parameters *v1alpha1.AuditPolicyPara
 	return nil
 }
 
-func prepareCreateSql(parameters *v1alpha1.AuditPolicyParameters) string {
-	query := fmt.Sprintf("CREATE AUDIT POLICY %s AUDITING %s", parameters.PolicyName, parameters.AuditStatus)
+func OptimizeAuditActions(actionStrings []string) []string {
```
Comment (Noel-Ch) [inline internal/clients/hana/auditpolicy/auditpolicy_client.go]: There is a lot of complexity added here. Is this just to reduce the number of queries, or are there any other purposes? Maybe it's worth testing how much this helps?

File: internal/utils/utils.go [hunk 2]
```diff
@@ -1,65 +1,87 @@
...
+func MapKeysToUpper[A comparable](input map[string]A) map[string]A {
+	upperMap := make(map[string]A, len(input))
+	for k, v := range input {
+		upperMap[strings.ToUpper(k)] = v
 	}
+	return upperMap
+}
 
-	return true
+func MapsEqual[A comparable](map1, map2 map[string]A) bool {
```
Comment (Noel-Ch) [inline internal/utils/utils.go]: This new implementation seems less efficient than the old one. Should we just keep it unchanged?

File: internal/clients/hana/auditpolicy/auditpolicy_client.go [hunk 3]
```diff
@@ -151,32 +155,249 @@ func (c Client) Delete(ctx context.Context, parameters *v1alpha1.AuditPolicyPara
...
+	for i := range actionStrings {
+		actionStrings[i] = strings.ReplaceAll(actionStrings[i], " FOR PRINCIPALS ALL USERS", "")
+	}
+	groupedActions := []string{}
+	parsedActions := []parsedAction{}
+	for _, actionString := range actionStrings {
+		actions, err := parseIntoActions(actionString)
+		if err != nil {
+			// In case of error, return original actions
+			return actionStrings
```
[the remark this answers is not in the document]
Comment (yamaceay) [reply internal/clients/hana/auditpolicy/auditpolicy_client.go]: Good question, I'm switching it back.
