### PR TITLE
fix: prevent spurious usergroup updates from HANA default parameters

### LINKED ISSUE #76: [BUG] Usergroup is continuously updated if not all parameters are set
**Describe the bug**
For the Usergroup (admin.hana.sap.crossplane.io/v1alpha1) resource reconciler continuously detect diff if not all the possible parameters are detected.

**Tested with Provider Version**
[v0.1.1](https://github.com/SAP/crossplane-provider-hana/releases/tag/v0.1.1)

**To Reproduce**
1. Create usergroup resource

```yaml
apiVersion: admin.hana.sap.crossplane.io/v1alpha1
kind: Usergroup
metadata:
  name: test-usergroup
spec:
  deletionPolicy: Orphan
  forProvider:
    parameters:
      maximum_unused_initial_password_lifetime: "365"
    usergroupName: TEST
  managementPolicies:
  - '*'
  providerConfigRef:
    name: providerconfig
```

2. Check the events:

```bash
Events:
  Type    Reason                   Age                       From                                            Message
  ----    ------                   ----                      ----                                            -------
  Normal  UpdatedExternalResource  2m38s (x3838 over 2d13h)  managed/usergroup.admin.hana.sap.crossplane.io  Successfully requested update of external resource
```

**Expected behavior**
Only observe the configured parameters (e.g., maximum_unused_initial_password_lifetime in this case) and send an update if they change.

**Additional context**

### PR DESCRIPTION
**Pull request by althaf1088**
This PR fixes issue #76.

## Problem
The UserGroup controller was triggering unnecessary reconciliation loops because it compared all parameters in the observed state (including HANA defaults) against the desired state (only user-specified parameters). This caused the controller to continuously attempt updates even when the user-specified parameters were correct.

### UserGroup Controller (internal/controller/usergroup/reconciler.go)
- Replace `utils.MapDiff()` with `utils.MapDiffOnlyDesired()` in both `upToDate()` and `Update()` methods
- Add comments explaining that only user-specified parameters should trigger updates

### Utils (internal/utils/utils.go)
- Add new `MapDiffOnlyDesired()` function that only compares keys present in the desired state
- Prevents false positives from HANA default parameters that weren't specified by the user

### Tests (internal/utils/utils_test.go)
- Add comprehensive test suite for `MapDiffOnlyDesired()` with 8 test cases covering:
  - Matching parameters with extra observed defaults
  - Differing parameter values
  - Missing parameters in observed state
  - Empty maps
  - Real-world scenario with HANA defaults

## Testing
All existing and new tests pass.

Fixes #76

### CODE REVIEW

**Review by CsDenes — APPROVED** [review]
LGTM. We don't handle the parameter remove scenarios. But it is ok as I think we can't remove these parameters and would not make sense to change back to default. In the documentation we will mention that this works in a `lax` way.

File: internal/utils/utils.go [hunk 1]
```diff
@@ -149,6 +149,22 @@ func MapDiff[K, V comparable](map1, map2 map[K]V) map[K]V {
 	return differenceMap
 }
 
+// MapDiffOnlyDesired compares only the keys that exist in the desired map.
+// This prevents comparing default values from observed state that weren't specified by the user.
+// Returns a map of parameters that need to be updated (keys from desired that differ in observed).
+func MapDiffOnlyDesired[K, V comparable](observed, desired map[K]V) map[K]V {
```
Comment (dwlou) [inline internal/utils/utils.go:155]: do I understand it correctly that this compares only those parameters explicitly specified in the CR `forProvider` but ignore any additional default might be provided by the hana itself? If so, maybe rename "desired" to sth more intuitive, e.g., mapDiffIgnoreDefault

Comment (althaf1088) [reply internal/utils/utils.go:155]: ignoring default is a subpart.. actual functionality is to check if there are any change to the desired value which is mentioned in the CR to what is present in hana DB, then it returns response
